apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
    dmVyLWNhQDE3MzAzNzY1MzgwHhcNMjQxMDMxMTIwODU4WhcNMzQxMDI5MTIwODU4
    WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3MzAzNzY1MzgwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAQPukxOuWp//BYYqspAAaCyQpm3hhTXrclAmMG6sO7Z
    p2m5onstCbiOYLHaXmjhtq6teCuU9Ndeo6ojpydPBPJCo0IwQDAOBgNVHQ8BAf8E
    BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUhUFE1zNx7Bx02tbXV6DW
    Mh5iL5EwCgYIKoZIzj0EAwIDSAAwRQIhAM8pdqld20/KqVhK5mZ468L5ZCxJeG/N
    vOvns52NU1IGAiAwfkKVPDXkoyt/spcfW7/oQDnQqjvzCzSUos4prY+N/A==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the kube-apiserver when using internal endpoints such as the internal service IP or kubernetes.default.svc. No other usage is guaranteed across distributions of Kubernetes clusters.
  name: kube-root-ca.crt
  namespace: media
