apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: public-share
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: public-share
