apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: kube-plex
    chart: kube-plex-0.2.7
    heritage: Helm
    release: plex
  name: plex-kube-plex
  namespace: media
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: pms
      port: 32400
      protocol: TCP
      targetPort: pms
  selector:
    app: plex
  sessionAffinity: None
  type: ClusterIP
